Fix Framework/ArrowTests/test/test_Arrow01.cxx on macos CI
Probably an interference from a recent alidist update, the effected unit test has
not been changed recently.

The CI build on macos failsin Framework/ArrowTests/test/test_Arrow01.cxx with error
```
 error: ignoring return value of function declared with 'warn_unused_result' attribute
 [-Werror,-Wunused-result]
```
Assigning the return value to variables to get rid of this.